export { VideoEditor, type VideoEditorMount, type VideoEditorOptions } from './VideoEditor';

export { Timeline } from '@opensource/timeline';
export type { TimelineOptions, TimelineState } from '@opensource/timeline';
export { CompositionPreview } from '@opensource/video-preview';
export type { CompositionPreviewOptions } from '@opensource/video-preview';
export {
  bindClipPreviewSync,
  TimelinePreviewSyncer,
  fromPreviewElementToTimelineClip,
  getTimelineClipZIndex,
  timelineClipToCanvasElement,
} from './clipPreviewSync';
export type { ClipPreviewSyncOptions } from './clipPreviewSync';
export {
  AnimationFrameLoop,
  bindEditorPlayback,
  EditorPlayback,
  type AnimationFrameLoopOptions,
  type EditorPlaybackOptions,
  type FrameCallback,
  type FrameContext,
} from './loop';
export {
  bindSidebarExport,
  previewElementsToComposition,
  downloadBlob,
  exportVideoFromPreview,
  rasterizeTextElement,
  DEFAULT_EXPORT_FORMAT,
  DEFAULT_EXPORT_FPS,
  DEFAULT_EXPORT_QUALITY,
  EXPORT_FPS_OPTIONS,
  EXPORT_QUALITY_BITRATES,
  resolveExportDimensions,
  resolveExportSettings,
  resolveOutputFilename,
  type BindSidebarExportOptions,
  type PreviewToCompositionOptions,
  type PreviewToCompositionResult,
  type ExportFormat,
  type ExportQuality,
  type ExportResolution,
  type ExportResolutionPreset,
  type ExportVideoOptions,
  type ExportVideoResult,
  type ResolvedExportSettings,
} from './export';
export type { ExportProgress } from '@opensource/gpu-video-encode';
export {
  bindProjectPersistence,
  captureProjectDocument,
  createEmptyProjectDocument,
  FileSystemProjectStore,
  IndexedDbProjectIndex,
  MediaAssetService,
  pickMediaFiles,
  pickProjectDirectory,
  ProjectSession,
  resolveProjectDocument,
  PROJECT_DOCUMENT_VERSION,
  PROJECT_JSON_FILENAME,
  PROJECT_MEDIA_DIR,
  type BindProjectPersistenceOptions,
  type ImportMediaResult,
  type PersistedMediaAsset,
  type ProjectDocument,
  type ProjectMetadata,
  type ProjectPersistenceApi,
  type ProjectPersistenceOptions,
  type ProjectPersistenceStatus,
} from './project';
export {
  bindMediaLibrary,
  MediaLibrary,
  MediaLibraryEventEmitter,
  MediaLibraryPanel,
  mountMediaLibraryPanel,
  addMediaToTimeline,
  mediaLibraryItemToAddClipInput,
  type AddMediaFromFileOptions,
  type BindMediaLibraryOptions,
  type MediaLibraryEventHandler,
  type MediaLibraryEventMap,
  type MediaLibraryEventName,
} from './mediaLibrary';
export {
  bindTranscription,
  TranscriptionPanel,
  TranscriptionWorkspace,
  configureTranscriptionEnv,
  TranscriptionService,
  TranscriptionEventEmitter,
  PipelineFactory,
  transcribe,
  audioBufferToFloat32Array,
  extractAudioFromMediaUrl,
  createMockTranscriptionResult,
  type BindTranscriptionOptions,
  type TranscriptionChunk,
  type TranscriptionEventHandler,
  type TranscriptionEventMap,
  type TranscriptionEventName,
  type TranscriptionOptions,
  type TranscriptionProgress,
  type TranscriptionResult,
  type TranscriptionUIEventHandler,
  type TranscriptionUIEventMap,
  type TranscriptionUIEventName,
} from './transcription';
export {
  Sidebar,
  mountSidebar,
  SidebarEventEmitter,
  SidebarView,
} from '@opensource/sidebar';
export type {
  SidebarOptions,
  SidebarEventMap,
  SidebarEventName,
  SidebarEventHandler,
  ExportSettings,
  MediaLibraryItem,
  ResolvedMediaInput,
  SidebarPanelId,
} from '@opensource/sidebar';
